name: Build and Push to ECR

on:
  push:
    branches: [main]
    paths:
      - "catalog-service/**"
      - "!catalog-service/README.md"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: catalog-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: catalog-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug OIDC Token Claims
        uses: actions/github-script@v7
        with:
          script: |
            const idToken = await core.getIDToken('sts.amazonaws.com');
            const payload = JSON.parse(
              Buffer.from(idToken.split('.')[1], 'base64').toString()
            );
            console.log(payload);

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::463623100443:role/github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .          
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # checkout the gitops repo code in to github runner
      - name: Checkout gitops code
        uses: actions/checkout@v4
        with:
          repository: pdgayan/ecom-gitops
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops-repo

      #update the correct k8 menifest file using yc tool
      - name: Install yq tool
        uses: mikefarah/yq@v4.44.3

      - name: update image tag in deployments and jobs
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"' $GITHUB_WORKSPACE/gitops-repo/catalog-service/deployment.yml

           yq -i '.spec.template.spec.containers[0].image = "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"' $GITHUB_WORKSPACE/gitops-repo/catalog-service/migration_job.yml

      # commit and push the updated version in to repo
      - name: commit and push changes to gitops manifest (catalog-deployment.yml image update)
        working-directory: gitops-repo
        run: |
          git config user.name "catalog-deploy-bot"
          git config user.email "catalog-deploy-bot@users.noreply.github.com"
          git add catalog-service/deployment.yml
          git add catalog-service/migration_job.yml
          git commit -m "Update catalog-service image to ${{ github.sha }}"
          git push
